config/routes.rb
Rails.application.routes.draw do
  resources :feeds do
    collection do
      get 'word_aggregator'
      post 'clear_entries'
    end
    member do
      get 'entries'
    end
  end
  resources :entries, only: [:index, :show]
  resources :categories
  resources :context_categories
  resources :single_word_blacklist_items, only: [:index] do
    collection do
      post 'batch_create'
    end
  end
  root 'feeds#index'
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :entries, dependent: :destroy
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy, :entries]

  def index
    @feeds = Feed.all
  end

  def show
  end

  def entries
    @entries = @feed.entries.order('published desc')
  end

  def new
    @feed = Feed.new
  end

  def edit
  end

  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def word_aggregator
    #@phrases = Phrase.joins(:phrase_entries).group("phrases.id").order("count(phrases.id) desc")
    @phrases = Phrase.joins(:phrase_entries).group("phrases.id").order("RANDOM()")
  end

  def clear_entries
    Entry.destroy_all
    redirect_to feeds_path
  end

  private
    def set_feed
      @feed = Feed.find(params[:id])
    end

    def feed_params
      params.require(:feed).permit(:name, :url, :description)
    end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_accordian_card.html.erb
<div class="card">
  <div class="card-header" role="tab" id="headingOne">
    <h5 class="mb-0">
      <a data-toggle="collapse" data-parent="#accordion" href="##{control_id}" aria-expanded="true" aria-controls="#{control_id}">
        <%= title %>
      </a>
    </h5>
  </div>

  <div id="#{control_id}" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
    <div class="card-block">
      <% entries.each do |entry| %>
        <%= link_to entry.title, entry_path(entry.id) %><br>
      <% end %>
    </div>
  </div>
</div>

app/views/feeds/_accordion_card.html.erb
<div class="accordion-card">
  <div role="tab" id="<%= header_id %>">
    <h5 class="mb-0">
      <a class="collapsed" data-toggle="collapse" data-parent="#<%= accordion_id %>" href="#<%= control_id %>" aria-expanded="false" aria-controls="<%= control_id %>">
        <%= title %>
      </a>
    </h5>
  </div>

  <div id="<%= control_id %>" class="collapse" role="tabpanel" aria-labelledby="<%= header_id %>">
    <div class="card-block">
      <% entries.each do |entry| %>
        <div class="article-entry"><%= link_to entry.title, entry_path(entry.id) %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/feeds/_form.html.erb
<%= form_for(feed) do |f| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/entries.html.erb
<div class="container">
  <% @entries.each do |entry| %>
    <div class="panel panel-default">
      <div class="panel-body">
        <%= link_to entry.title, entry %> 
        <% if entry.published %>
          - <i> published <%= time_ago_in_words(entry.published) %> ago.</i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.name %></td>
        <td><%= feed.url %></td>
        <td><%= feed.description %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Entries', entries_feed_path(feed) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

<br><br><%= link_to 'Clear Entries', clear_entries_feeds_path, method: :post, data: { confirm: 'Are you sure?' } %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @feed.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @feed.description %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/word_aggregator.html.erb
<div class="card trending-articles">
  <h3 class="card-header">Trending Articles</h3>
  <div class="card-block">
    <% Entry.most_phrases.each do |info| %>
      <% entry = Entry.find(info[0]) %>
      <div><%= link_to entry.title, entry_path(entry.id) %></div>
    <% end %>
  </div>
</div><br><br>

<h2>Trending Topics</h2>
<br>
<div class="color-guide-section">
  <div class="color-guide top-tech-companies"></div> - Top Tech Companies
  <div class="color-guide popular-tech"></div> - Popular Tech
  <div class="color-guide tech-topics"></div> - Tech Topics
  <div class="color-guide tech-products"></div> - Tech Products
  <div class="color-guide tech-companies"></div> - Tech Companies
  <div class="color-guide apple-stuff"></div> - Apple Stuff
  <div class="color-guide hardware"></div> - Hardware
  <div class="color-guide operating-systems"></div> - Operating Systems
  <div class="color-guide programming-and-development"></div> - Programming & Development
  <div class="color-guide legal-and-political-entities"></div> - Legal & Political
  <div class="color-guide it-topics"></div> - IT Topics
</div>
<br>
<div class="card-columns">
  <% @phrases.each_with_index do |phrase, idx| %>
    <div class="feed-card card">
      <div class="thing-category <%= phrase.category.category.name.downcase.gsub(" ", "-") if phrase.category %>"></div>
      <div class="feed-card-contents">
        <div class="phrase-header"><%= "#{phrase.example} (#{phrase.count})" %></div>

        <% if false #phrase.similar_phrases.present? %>
          Similar phrases:<br>
          <% phrase.similar_phrases.each do |similar_phrase| %>
            <%= "#{similar_phrase[:example]} - #{similar_phrase[:count]} shared articles" %><br>
          <% end %>
          <br>
        <% end %>

        <% element_count = 1 %>
        <% all_entries = phrase.entries.joins(:context_categories) %>
        <div id="accordion<%= idx %>" role="tablist" aria-multiselectable="true">
          <% phrase.entry_display_array.each do |display_info| %>
            <% title = "#{display_info[:category].name.titleize} (#{display_info[:entries].size})" %>
            <% control_id = "#{phrase.content.gsub(" ", "-")}-collapse#{element_count}" %>
            <% header_id = "#{phrase.content.gsub(" ", "-")}-header#{element_count}" %>
            <%= render partial: "accordion_card", locals: {title: title, entries: display_info[:entries], control_id: control_id, header_id: header_id, accordion_id: "accordion#{idx}"} %>
            <% element_count = element_count + 1 %>
          <% end %>

          <% title = "All Articles:" %>
          <% control_id = "#{phrase.content.gsub(" ", "-")}-collapse#{element_count}" %>
          <% header_id = "#{phrase.content.gsub(" ", "-")}-header#{element_count}" %>
          <%= render partial: "accordion_card", locals: {title: title, entries: phrase.entries, control_id: control_id, header_id: header_id, accordion_id: "accordion#{idx}"} %>
        </div>
      </div>
    </div>
  <% end %>
</div>