config/routes.rb
Rails.application.routes.draw do
  resources :feeds do
    collection do
      get 'word_aggregator'
      post 'clear_entries'
    end
    member do
      get 'entries'
    end
  end
  resources :entries, only: [:index, :show]
  resources :categories
  resources :context_categories
  resources :single_word_blacklist_items, only: [:index] do
    collection do
      post 'batch_create'
    end
  end
  root 'feeds#index'
end

app/models/context_category.rb
class ContextCategory < ApplicationRecord
  has_many :context_words, dependent: :destroy
  has_many :entry_contexts, dependent: :destroy
  has_many :entries, through: :entry_contexts
  has_many :phrases, through: :entries
end

app/controllers/context_categories_controller.rb
class ContextCategoriesController < ApplicationController
  before_action :set_context, only: [:show, :destroy]

  def index
    @contexts = ContextCategory.order('created_at desc')
    @context = ContextCategory.new
  end

  def show
  end

  def destroy
    @context.destroy
    redirect_to context_categories_path, notice: 'Context was successfully destroyed.'
  end

  def create
    file = params[:context_category][:context_file]

    file_name = params[:context_category][:name]
    return if file_name.empty?
    priority = params[:context_category][:priority].present? ? params[:context_category][:priority] : 3

    ContextCategory.where(name: file_name).destroy_all
    context = ContextCategory.create!(name: file_name, priority: priority)

    file_contents = file.read
    file_contents.gsub!(/\r\n?/, "\n")

    file_contents.each_line do |line|
      ContextWord.create!(context_category_id: context.id, name: line.gsub("\n",''))
    end

    redirect_to context_categories_path
  end

  private

  def set_context
    @context = ContextCategory.find(params[:id])
  end
end

app/views/context_categories/index.html.erb
<h2>Context Categories</h2>

<h3>Add a new context</h3><br>
<%= form_for @context do |f| %>

  Display Name: <%= f.text_field :name %><br><br>
  Priority: <%= f.number_field :priority %><br><br>
  <%= f.file_field :context_file %><br><br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<br>
<br>

<h3>Current Categories</h3>
<% @contexts.each do |context| %>
  <%= link_to context.name, context_category_path(context.id) %><br>
  <%= "Priority: #{context.priority}" %><br>
  <%= link_to 'Destroy', context, method: :delete, data: { confirm: 'Are you sure?' } %><br><br>
<% end %>

app/views/context_categories/show.html.erb
<h1><%= @context.name.pluralize %></h1>

<% @context.context_words.each do |word| %>
  <%= word.name %><br>
<% end %>