config/routes.rb
Rails.application.routes.draw do
  resources :feeds do
    collection do
      get 'word_aggregator'
      post 'clear_entries'
    end
    member do
      get 'entries'
    end
  end
  resources :entries, only: [:index, :show]
  resources :categories
  resources :context_categories
  resources :single_word_blacklist_items, only: [:index] do
    collection do
      post 'batch_create'
    end
  end
  root 'feeds#index'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :destroy]

  def index
    @categories = Category.order('created_at desc')
    @category = Category.new
  end

  def show
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  def create
    file = params[:category][:category_file]

    file_name = params[:category][:name]
    return if file_name.empty?
    priority = params[:category][:priority].present? ? params[:category][:priority] : 3

    Category.where(name: file_name).destroy_all
    category = Category.create!(name: file_name, priority: priority)

    file_contents = file.read
    file_contents.gsub!(/\r\n?/, "\n")

    file_contents.each_line do |line|
      Item.create!(category_id: category.id, name: line.gsub("\n",''))
    end

    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end
end

app/views/categories/index.html.erb
<h2>Things</h2>

<h3>Add a new category</h3><br>
<%= form_for @category do |f| %>

  Display Name: <%= f.text_field :name %><br><br>
  Priority: <%= f.number_field :priority %><br><br>
  <%= f.file_field :category_file %><br><br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<br>
<br>

<h3>Current Categories</h3>
<% @categories.each do |category| %>
  <%= link_to category.name, category_path(category.id) %><br>
  <%= "Priority: #{category.priority}" %><br>
  <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %><br><br>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name.pluralize %></h1>

<% @category.items.each do |item| %>
  <%= item.name %><br>
<% end %>